# This workflow will installPython dependencies, run tests and lint with a single version of Python
name: Meet_Greet Schedule

on:
  schedule:
    - cron: '0 14 * * *'

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PEM_KEY: ${{ secrets.SSH_PEM_KEY }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  BRZW_CLIENT_ID: ${{ secrets.BRZW_CLIENT_ID }}
  BRZW_CLIENT_SECRET: ${{ secrets.BRZW_CLIENT_SECRET }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pymysql sshtunnel pandas requests
        #working out of the meet_and_greet folder

      - name: Run Script
        run: |
          echo "${{ secrets.SSH_PEM_KEY }}" | tr -d '\r' > beachfrontvr.pem
          python3 ./arrival_query.py
