# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Dropbox Update

# BEGIN: 7c8f1d3fj5xq
on:
  schedule:
    - cron: "0 * * * *"
# END: 7c8f1d3fj5xq


env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PEM_KEY: ${{ secrets.SSH_PEM_KEY }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
  DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
  DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pymysql sshtunnel dropbox datetime
    - name: Run Script
      run: |
        echo "${{ secrets.SSH_PEM_KEY }}" | tr -d '\r' > key.pem
        python3 database_to_tableau.py

